# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1st-2nd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUiType
import os
from os import path
import sys
import numpy as np
import pyqtgraph as pg
from pyqtgraph import PlotWidget
import time
import datetime
class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.setEnabled(True)
        mainwindow.resize(1297, 751)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 60, 911, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = pg.PlotWidget(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.graphicsView_3 = pg.PlotWidget(self.verticalLayoutWidget)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout.addWidget(self.graphicsView_3)
        self.graphicsView_2 = pg.PlotWidget(self.verticalLayoutWidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 50, 111, 631))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1180, 60, 111, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.channels = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.channels.setObjectName("channels")
        self.verticalLayout_3.addWidget(self.channels)
        self.resume = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.resume.setObjectName("resume")
        self.verticalLayout_3.addWidget(self.resume)
        self.pause = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pause.setObjectName("pause")
        self.verticalLayout_3.addWidget(self.pause)
        self.clear = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.clear.setObjectName("clear")
        self.verticalLayout_3.addWidget(self.clear)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(160, 540, 911, 131))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1090, 90, 71, 71))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.zoomin1 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.zoomin1.setObjectName("zoomin1")
        self.verticalLayout_13.addWidget(self.zoomin1)
        self.zoomout1 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.zoomout1.setObjectName("zoomout1")
        self.verticalLayout_13.addWidget(self.zoomout1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1090, 240, 71, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.zoomin2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.zoomin2.setObjectName("zoomin2")
        self.verticalLayout_14.addWidget(self.zoomin2)
        self.zoomout2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.zoomout2.setObjectName("zoomout2")
        self.verticalLayout_14.addWidget(self.zoomout2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1090, 400, 71, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.zoomin3 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.zoomin3.setObjectName("zoomin3")
        self.verticalLayout_15.addWidget(self.zoomin3)
        self.zoomout3 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.zoomout3.setObjectName("zoomout3")
        self.verticalLayout_15.addWidget(self.zoomout3)
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setBaseSize(QtCore.QSize(4, 8))
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1297, 26))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menusignal_processing = QtWidgets.QMenu(self.menubar)
        self.menusignal_processing.setBaseSize(QtCore.QSize(7, 7))
        self.menusignal_processing.setObjectName("menusignal_processing")
        self.open_ch1 = QtWidgets.QMenu(self.menubar)
        self.open_ch1.setObjectName("open_ch1")
        self.open_ch2 = QtWidgets.QMenu(self.menubar)
        self.open_ch2.setObjectName("open_ch2")
        self.open_ch3 = QtWidgets.QMenu(self.menubar)
        self.open_ch3.setObjectName("open_ch3")
        self.spect = QtWidgets.QMenu(self.menubar)
        self.spect.setObjectName("spect")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        mainwindow.setMenuBar(self.menubar)
        self.actionopen = QtWidgets.QAction(mainwindow)
        self.actionopen.setObjectName("actionopen")
        self.actionhelp = QtWidgets.QAction(mainwindow)
        self.actionhelp.setObjectName("actionhelp")
        self.close = QtWidgets.QAction(mainwindow)
        self.close.setObjectName("close")
        self.actionhelp_2 = QtWidgets.QAction(mainwindow)
        self.actionhelp_2.setObjectName("actionhelp_2")
        self.about = QtWidgets.QAction(mainwindow)
        self.about.setObjectName("about")
        self.menusignal_processing.addAction(self.about)
        self.menusignal_processing.addAction(self.close)
        self.menubar.addAction(self.menusignal_processing.menuAction())
        self.menubar.addAction(self.open_ch1.menuAction())
        self.menubar.addAction(self.open_ch2.menuAction())
        self.menubar.addAction(self.open_ch3.menuAction())
        self.menubar.addAction(self.spect.menuAction())
        self.menubar.addAction(self.help.menuAction())
        #timer for qt
        self.timer1 = QtCore.QTimer()
        self.timer2 = QtCore.QTimer()
        self.timer3 = QtCore.QTimer()


        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

#reading dataaa ************************
    def read_data(self,ch):
        path=str(r"C:\Users\Lenovo\Desktop\1st_task_tamer\emg.csv")
        data=np.genfromtxt(path,delimiter = ' ')
        x1=data[: , 0]
        y1 =data[: , 1]
        if ch==1:
            self.x1= list(x1[:])
            self.y1= list(y1[:])
        if ch==2:
            self.x2= list(x1[:])
            self.y2= list(y1[:])
        if ch==3:
            self.x3= list(x1[:])
            self.y3= list(y1[:])
#function in qt timer to update the data
    def update1(self):
        if self.st_x1>len(self.x1):
            self.st_x1=10
        x=self.x1[:self.st_x1]
        y=self.y1[:self.st_x1]
        self.st_x1+=10
        self.graphicsView.plot(x,y,pen=pg.mkPen('b', width=1))
    def update2(self):
            x=self.x2[:self.st_x2]
            y=self.y2[:self.st_x2]
            self.st_x2+=10
            self.graphicsView_3.plot(x,y,pen=pg.mkPen('r', width=2))
            if self.st_x2>len(self.x2):
                self.st_x2=0
    def update3(self):
            x=self.x3[:self.st_x3]
            y=self.y3[:self.st_x3]
            self.st_x3+=10
            self.graphicsView_2.plot(x,y,pen=pg.mkPen('g', width=3))
            if self.st_x3>len(self.x3):
                self.st_x3=0
#playing data on adding the file

    def play1(self):
        self.read_data(1)
        self.timer1.start()
        self.st_x1=10
        self.timer1.setInterval(100)
        self.timer1.timeout.connect(self.update1)
        self.timer1.start()

    def play2(self):
        self.read_data(2)
        self.timer2.start()
        self.st_x2=10
        self.timer2.setInterval(100)
        self.timer2.timeout.connect(self.update2)
        self.timer2.start()

    def play3(self):
        self.read_data(3)
        self.timer3.start()
        self.st_x3=10
        self.timer3.setInterval(100)
        self.timer3.timeout.connect(self.update3)
        self.timer3.start()


#pause
    def stop(self):
        self.timer1.stop()
        self.timer2.stop()
        self.timer3.stop()

#to clear data
    def delete(self):
        self.graphicsView.clear()
        self.graphicsView_2.clear()
        self.graphicsView_3.clear()
        self.stop()



    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MainWindow"))
        self.label.setText(_translate("mainwindow", "channel 1"))
        self.label_2.setText(_translate("mainwindow", "channel 2"))
        self.label_3.setText(_translate("mainwindow", "channel 3"))
        self.label_4.setText(_translate("mainwindow", "spectrogram"))
        self.resume.setText(_translate("mainwindow", "play"))
        self.pause.setText(_translate("mainwindow", "pause"))
        self.clear.setText(_translate("mainwindow", "clear"))
        self.zoomin1.setText(_translate("mainwindow", "+"))
        self.zoomout1.setText(_translate("mainwindow", "-"))
        self.zoomin2.setText(_translate("mainwindow", "+"))
        self.zoomout2.setText(_translate("mainwindow", "-"))
        self.zoomin3.setText(_translate("mainwindow", "+"))
        self.zoomout3.setText(_translate("mainwindow", "-"))
        self.menusignal_processing.setTitle(_translate("mainwindow", "file"))
        self.open_ch1.setTitle(_translate("mainwindow", "channel 1"))
        self.open_ch2.setTitle(_translate("mainwindow", "channel 2"))
        self.open_ch3.setTitle(_translate("mainwindow", "channel 3"))
        self.spect.setTitle(_translate("mainwindow", "spectrogram"))
        self.help.setTitle(_translate("mainwindow", "help"))
        self.actionopen.setText(_translate("mainwindow", "open "))
        self.actionhelp.setText(_translate("mainwindow", "help"))
        self.close.setText(_translate("mainwindow", "close "))
        self.actionhelp_2.setText(_translate("mainwindow", "help "))
        self.about.setText(_translate("mainwindow", "about"))
        #actions

        self.resume.clicked.connect(lambda:self.play1())

        self.pause.clicked.connect(lambda:self.stop())

        self.clear.clicked.connect(lambda:self.delete())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
